export const FETCH_CRYPTO_INFO = 'FETCH_CRYPTO_INFO';
export const FETCH_FIAT_CURRENCIES = 'FETCH_FIAT_CURRENCIES';
export const FETCH_NEWS = 'FETCH_NEWS';
export const CURRENT_FIAT = 'CURRENT_FIAT';
